import type { VoiceProfile } from "./types";

export const VOICE_PROFILES: VoiceProfile[] = [
  {
    id: "calm-female",
    name: "Calm Female",
    emoji: "🧘",
    gender: "female",
    age: "mature",
    persona: "calm",
    accent: "us",
    description: "Soothing, balanced female voice — great for long conversations",
    voiceHints: ["Female", "Calm", "Soft", "Natural", "Samantha", "Google UK Female"],
    defaultPitch: 1.0,
    defaultRate: 0.9,
  },
  {
    id: "professional-male",
    name: "Professional Male",
    emoji: "👔",
    gender: "male",
    age: "mature",
    persona: "professional",
    accent: "us",
    description: "Clear, authoritative male voice — ideal for work and analysis",
    voiceHints: ["Male", "Professional", "Deep", "Natural", "Google US Male", "Alex"],
    defaultPitch: 0.85,
    defaultRate: 0.95,
  },
  {
    id: "energetic-young",
    name: "Energetic Young",
    emoji: "⚡",
    gender: "female",
    age: "young",
    persona: "energetic",
    accent: "us",
    description: "Bright, lively voice — perfect for casual chat and stories",
    voiceHints: ["Young", "Bright", "Upbeat", "Female", "Google UK Female"],
    defaultPitch: 1.3,
    defaultRate: 1.15,
  },
  {
    id: "friendly-female",
    name: "Friendly Female",
    emoji: "😊",
    gender: "female",
    age: "young",
    persona: "friendly",
    accent: "us",
    description: "Warm, approachable voice — great for everyday help",
    voiceHints: ["Female", "Friendly", "Warm", "Natural", "Samantha"],
    defaultPitch: 1.1,
    defaultRate: 1.0,
  },
  {
    id: "calm-male",
    name: "Calm Male",
    emoji: "🌊",
    gender: "male",
    age: "mature",
    persona: "calm",
    accent: "us",
    description: "Steady, reassuring male voice — for focused discussions",
    voiceHints: ["Male", "Calm", "Deep", "Natural", "Google US Male"],
    defaultPitch: 0.9,
    defaultRate: 0.85,
  },
  {
    id: "professional-female",
    name: "Professional Female",
    emoji: "💼",
    gender: "female",
    age: "mature",
    persona: "professional",
    accent: "us",
    description: "Polished, articulate female voice — for business and presentations",
    voiceHints: ["Female", "Professional", "Clear", "Natural"],
    defaultPitch: 1.0,
    defaultRate: 0.95,
  },
  {
    id: "energetic-male",
    name: "Energetic Male",
    emoji: "🔥",
    gender: "male",
    age: "young",
    persona: "energetic",
    accent: "us",
    description: "Dynamic, enthusiastic male voice — for motivational content",
    voiceHints: ["Male", "Young", "Upbeat", "Google UK Male"],
    defaultPitch: 1.2,
    defaultRate: 1.1,
  },
  {
    id: "friendly-male",
    name: "Friendly Male",
    emoji: "🤝",
    gender: "male",
    age: "young",
    persona: "friendly",
    accent: "us",
    description: "Easygoing, relatable male voice — for natural conversation",
    voiceHints: ["Male", "Friendly", "Warm", "Natural"],
    defaultPitch: 1.0,
    defaultRate: 1.0,
  },
];

export function getVoiceProfile(id: string): VoiceProfile | undefined {
  return VOICE_PROFILES.find((v) => v.id === id);
}

export function getVoiceProfileByPersona(persona: string): VoiceProfile {
  return VOICE_PROFILES.find((v) => v.persona === persona) || VOICE_PROFILES[0];
}
